flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- bytestring-builder-0.10.8.1.0
- io-streams-1.3.6.1
- io-streams-haproxy-1.0.0.1
- readable-0.3.1
- regex-base-0.93.2
- regex-posix-0.95.2
- snap-core-1.0.2.0
- snap-server-1.0.2.0
resolver: ghc-8.0.2
