flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- adjunctions-4.3
- blaze-html-0.8.1.3
- blaze-markup-0.7.1.1
- bson-0.3.2.3
- bytestring-builder-0.10.8.1.0
- cabal-doctest-1.0.2
- cipher-aes-0.2.11
- clientsession-0.9.1.2
- configurator-0.3.0.0
- cpphs-1.20.5
- cprng-aes-0.6.1
- crypto-api-0.13.2
- crypto-cipher-types-0.0.9
- crypto-random-0.0.9
- data-binary-ieee754-0.4.4
- data-default-0.7.1.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- digestive-functors-0.8.2.0
- digestive-functors-heist-0.8.7.0
- digestive-functors-snap-0.7.0.0
- directory-tree-0.12.1
- entropy-0.3.7
- fail-4.9.0.0
- haskell-src-exts-1.19.1
- haskell-src-meta-0.8
- heist-1.0.1.0
- io-streams-1.3.6.1
- io-streams-haproxy-1.0.0.1
- jmacro-0.6.14
- kan-extensions-5.0.2
- lens-4.15.2
- loop-0.3.0
- map-syntax-0.2.0.2
- math-functions-0.2.1.0
- matrix-0.3.5.0
- mongoDB-2.3.0
- mwc-random-0.13.6.0
- nonce-1.0.4
- parallel-3.2.1.1
- parseargs-0.2.0.8
- pcre-light-0.4.0.4
- polyparse-1.12
- pureMD5-2.1.3
- pwstore-fast-2.4.4
- random-shuffle-0.0.4
- readable-0.3.1
- reflection-2.1.2
- regex-base-0.93.2
- regex-posix-0.95.2
- securemem-0.1.9
- skein-1.0.9.4
- snap-1.0.0.1
- snap-core-1.0.2.0
- snap-extras-0.12.0.0
- snap-server-1.0.2.0
- vector-th-unbox-0.2.1.6
- wl-pprint-text-1.1.1.0
- xmlhtml-0.2.4
resolver: ghc-8.0.2
